### PR TITLE
PW-4431 allow guest customers to complete failed payment

### LINKED ISSUE #152: Authentication error for guest customer completing failed payment
**Describe the bug**
Guest customers are not able to complete a payment after a failed payment. API call made to `store-api.order.set-payment` [requires login](https://github.com/shopware/platform/blob/trunk/src/Core/Checkout/Order/SalesChannel/SetPaymentOrderRoute.php#L89) and we get this 403 response (see screenshot).

**To Reproduce**
1. Add product to cart and proceed to checkout as guest
2. Select a failing payment method (e.g card with wrong CVC)
3. Click the 'Change payment method' link in the resulting error message.
4. Attempt to complete payment

**Expected behavior**
Second attempt at payment should not get stuck with error

**Screenshots**
Screen Shot 2021-03-26 at 5 14 48 PM

### PR DESCRIPTION
**Pull request by peterojo**
## Summary

Shopware's route for updating the payment method of an order [requires login](https://github.com/shopware/platform/blob/trunk/src/Core/Checkout/Order/SalesChannel/SetPaymentOrderRoute.php#L89) and does not allows guest access, this breaks the payment functionality for guest customers attempting to complete a previously failed payment.
This is a workaround to fix it by creating a custom route that updates the payment method of the order
## Tested scenarios

Second attempt after failed payment
second attempt payment with wallet payment (e.g google pay)
all the above with v6.3.3.1

**Fixed issue**:  Resolves #152

### CODE REVIEW

File: src/Controller/StoreApiController.php [hunk 1]
```diff
@@ -212,4 +244,88 @@ public function getPaymentStatus(Request $request, SalesChannelContext $context)
...
+     * @OA\Post(
+     *      path="/adyen/set-payment",
+     *      summary="set payment for an order",
+     *      operationId="orderSetPayment",
+     *      tags={"Store API", "Account"},
+     *      @OA\RequestBody(
+     *          required=true,
+     *          @OA\JsonContent(
+     *              @OA\Property(property="paymentMethodId", description="The id of new paymentMethod", type="string"),
+     *              @OA\Property(property="orderId", description="The id of the order", type="string")
```
Comment (acampos1916) [inline src/Controller/StoreApiController.php:259]:
```suggestion
     *              @OA\Property(property="paymentMethodId", description="The ID of the new paymentMethod", type="string"),
     *              @OA\Property(property="orderId", description="The ID of the order", type="string")
```

Comment (acampos1916) [reply src/Controller/StoreApiController.php:259]: I see now that this is copied from SetPaymentOrderRoute.php

**Review by acampos1916 — DISMISSED** [review]

File: src/Controller/StoreApiController.php (hunk 1 above)
Comment (peterojo) [reply src/Controller/StoreApiController.php]: Yes I will push for changes to be made in the core, so that we don't have to do this workaround

**Review by acampos1916 — APPROVED** [review]

**Review by cyattilakiss — APPROVED** [review]
